language: ruby
rvm:
- 2.1

before_script:
 - chmod +x ./script/cibuild # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
script:
  - ./script/cibuild
  - ./script/deploy-gh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - gh-pages     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - GH_REF: github.com/the-engine-room/library.git
  - secure: "HpMZM1kV9AAbGjXrGOF8f6JPHA4XUFTVN6s9krhrGSxb8O0eLzwyZ1vM7zFqee2MmgssAo7IeLA4Iu4pkIeCFHfp5/wQRM5tlMDdFuMeO+Jwol57J+0AyIUhQPazU/FF3UYxEIqC++7cdvNSaDLrijwgxiU3r2MqB5Nc85yb5sjoEJtQbzca+X0vHy99hk6Rl/BXXkUi49RsLtjszRHCVj3URdPUGH2aMwWKO5QtVuSWFyGdEGFAUaRFNAJcLPLkmNW/VVMoTLw1cUNjdAnn+EUcCmg8UYwkzIP/dkJeESlEIZbTJx2wzRTMcYMcU4WilcnGIf+/JoZdCNYrlYoUBowAud7pb8A2p9foII9lqO4YQBfXsWt0nsKZrYNYcPMIbB6VuV2GFuFmwixUHgICZWlWw6QYc7Hke5fbT9xNXAtnjmyIeOsw8ms4pmUza8sTgUrxV5j6iV+u7PJofnigj30xFPDWqOwAeZ9cjnl9nYAbRf7g7CYub6GrnBBKbWZWXbFSo7UtTdI3S1TJqHvsa7hINI0A3O8xIUqRXS7Zc97mB1NNgzcCsavH5FZ9zkdGBEfuoGNot+t45Ya1NptIzPjFM66HgL+fk5LcZjIT5l7alaainFukfkBrDdHpyltYcnYA5DHGdkTJ6ehLO4J9x+eWgu/Vfk/TqRK9K22lMPc="
    
sudo: false # route your build to the container-based infrastructure for a faster build    
